### PR TITLE
init plot graphs

### PR DESCRIPTION
**Pull request by madzhun**
damn, it is because I did it in this repo. Do you want me to change the location?

### CODE REVIEW

**Review by viveshok — APPROVED** [review]

**Comment by viveshok** [comment]
no thats good please merge

**Comment by madzhun** [comment]
and what to do with inf which isn't shown in graphs?

**Comment by viveshok** [comment]
> and what to do with inf which isn't shown in graphs?

I'll add it myself

**Comment by madzhun** [comment]
ok, thank you

**Pull request merged**
